### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by radudang** [blocoio/cardcase#6]
Hello! I saw your existing logo and I want to propose a logo that can be more eyecatching.
https://utopian.io/utopian-io/@radudangratian/logo-proposal-for-card-case
I hope you will like it !

**Comment by sdsantos** [comment]
@radudang thank you for your contribution.

We agree that the icon could be more clear about the app purpose. But it's part of the app identify, the logo, UI/UX, illustrations, etc.. It shouldn't be considered separately from the rest. And it should reflect the app values like being easy to use and friendly.

Of course, since the app is open source, you are free to fork our repository and build your own version if that icon in mind.
